stages:
  - build
  - test
  - deploy

build-frontend-job:
  stage: build
  image: node:lts-alpine
  script:
    - cd frontend
    - npm install -g @vue/cli
    - npm install
    - npm run build
  environment: production

build-backend-job:
  stage: build
  image: node:lts-alpine
  script:
    - cd backend
    - npm install
    - npm build
  environment: production

test-job:
  stage: test
  script:
    - echo "This job executes tests."
    - sleep 20
    - echo "Success executing dummy tests!"
  environment: production

deploy1-prod:
  stage: deploy
  when: on_success
  script:
    - echo "I am pushing to dockerhub... or pretending to..."
  environment: production

deploy2-prod:
  stage: deploy
  when: on_failure
  script:
    - echo "Well now I'm not doing it."
  environment: production
