stages:
  - build
  - test
  - deploy

variables:
  DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
  DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - name: docker:19.03.12-dind

build-job:
  stage: build
  image: node:16-alpine
  script:
    - cd frontend
    - npm install
    - cd ../backend
    - npm install
  artifacts:
    expire_in: 1 hour
    paths:
      - frontend/dist
      - backend/build

test-job:
  stage: test
  image: node:16-alpine
  script:
    - echo "Executing unit tests for frontend and backend"
    # insert command for tests here!!!
    - echo "Tests passed successfully!"
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  image: docker:19.03.12
  script:
    - echo "Logging into DockerHub..."
    - echo $DOCKERHUB_USERNAME
    - echo $DOCKERHUB_PASSWORD
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - cd frontend
    - docker build -t $DOCKERHUB_USERNAME/campusconnect_frontend .
    - docker push $DOCKERHUB_USERNAME/campusconnect_frontend
    - cd ../backend
    - docker build -t $DOCKERHUB_USERNAME/campusconnect_backend .
    - docker push $DOCKERHUB_USERNAME/campusconnect_backend
  dependencies:
    - test-job
