stages:
  - build
  - test
  - docker-build
  - docker-push

variables:
  DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
  DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD

before_script:
  - echo "Logging into DockerHub..."
  - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

build-frontend-job:
  stage: build
  image: node:16-alpine
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist
  only:
    - main

build-backend-job:
  stage: build
  image: node:16-alpine
  script:
    - cd backend
    - npm install
    - npm run build
  artifacts:
    paths:
      - backend/build
  only:
    - main

test-job:
  stage: test
  image: node:16-alpine
  script:
    - echo "Executing unit tests for frontend and backend"
    # add commands for tests hereeeeeee
    - echo "Tests passed successfully!"
  dependencies:
    - build-frontend-job
    - build-backend-job

build-docker-frontend:
  stage: docker-build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - cd frontend
    - docker build -t $DOCKERHUB_USERNAME/campusconnect_frontend .
  only:
    - main
  dependencies:
    - test-job

build-docker-backend:
  stage: docker-build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - cd backend
    - docker build -t $DOCKERHUB_USERNAME/campusconnect_backend .
  only:
    - main
  dependencies:
    - test-job

push-docker-images:
  stage: docker-push
  image: docker:19.03.12
  script:
    - docker push $DOCKERHUB_USERNAME/campusconnect_frontend
    - docker push $DOCKERHUB_USERNAME/campusconnect_backend
  only:
    - main
  dependencies:
    - build-docker-frontend
    - build-docker-backend
